"""
ATDD: Acceptance tests for anki-writer (anki_writer.py) — Dual-service architecture.

TDD Phase: These tests define the expected API contract for the anki-writer service
in the new dual-service architecture (replaces AnkiConnect integration in old main.py).

P0 Tests (Critical Path):
  AW-P0-01: POST /add-word with word + sentence — success, returns note_id
  AW-P0-02: POST /add-word with duplicate word — returns 422 with "duplicate:"
  AW-P0-03: POST /add-word with empty word — returns 422 with "invalid:"
  AW-P0-04: GET /health — returns status: ok, collection_accessible: bool

Mock Strategy:
  - app.state.ldoce5_client: AsyncMock (injected directly, bypasses lifespan)
  - anki_writer._add_note_and_sync: patched per-test via unittest.mock.patch
    (avoids importing the anki package, which is not available in dev/CI)

Generated by: TEA ATDD Workflow (2026-03-03)
Story: iphone-anki-sync dual-service migration
"""

import os
import tempfile
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
import pytest_asyncio
from httpx import AsyncClient, ASGITransport, Response

import anki_writer


# ---------------------------------------------------------------------------
# Test data: sample ldoce5-api /lookup response consumed by anki-writer
# ---------------------------------------------------------------------------

SAMPLE_LDOCE5_RESPONSE = {
    "word": "happy",
    "pronunciation": "/ˈhæp.i/",
    "senses": [
        {
            "index": 0,
            "pos": "adjective",
            "sense_num": 1,
            "definition": "feeling or showing pleasure and contentment",
            "definition_html": (
                '<span class="POS">adjective</span>'
                '<span class="Sense">'
                '<span class="DEF">feeling or showing pleasure and contentment</span>'
                '<span class="EXAMPLE"><span class="BASE">She seemed genuinely happy.</span></span>'
                "</span>"
            ),
            "example": "She seemed genuinely happy.",
            "ai_selected": True,
        }
    ],
    "selected_sense_index": 0,
    "audio": {
        "uk": {"filename": "GB_happy0005.mp3", "url": "/audio/GB_happy0005.mp3"},
        "us": {"filename": "US_happy0005.mp3", "url": "/audio/US_happy0005.mp3"},
    },
    "warning": None,
}


def _make_mock_lookup_response():
    """Return a MagicMock mimicking a successful httpx response for /lookup.

    httpx.Response(200, json=...) fails in tests because raise_for_status()
    requires self.request to be set (httpx ≥0.24 raises RuntimeError otherwise).
    A MagicMock sidesteps this: raise_for_status() is a no-op MagicMock and
    .json() returns the real dict.
    """
    mock_resp = MagicMock()
    mock_resp.status_code = 200
    mock_resp.raise_for_status = MagicMock()
    mock_resp.json.return_value = SAMPLE_LDOCE5_RESPONSE
    mock_resp.content = b"fake_audio_bytes"
    return mock_resp


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest_asyncio.fixture
async def aw_client():
    """Yield (AsyncClient, mock_ldoce5) for anki-writer tests.

    Sets app.state.ldoce5_client directly — ASGITransport does NOT trigger
    the ASGI lifespan, so we bypass it and inject mocks into state ourselves.

    Note: _add_note_and_sync is NOT patched at fixture level — patch it
    per-test to control success/failure scenarios independently.
    """
    mock_ldoce5 = AsyncMock()
    anki_writer.app.state.ldoce5_client = mock_ldoce5

    async with AsyncClient(
        transport=ASGITransport(app=anki_writer.app), base_url="http://test"
    ) as ac:
        yield ac, mock_ldoce5

    # Clean up state between tests
    try:
        delattr(anki_writer.app.state, "ldoce5_client")
    except AttributeError:
        pass


# ---------------------------------------------------------------------------
# P0 Tests — Critical path (must all pass before any other work proceeds)
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_add_word_success(aw_client):
    """AW-P0-01: POST /add-word — success, returns note_id.

    Acceptance Criterion:
      Returns 200 with note_id, sense_used (0), word (lowercased), definition.
      Word is normalised to lowercase before lookup.
    """
    ac, mock_ldoce5 = aw_client
    mock_ldoce5.get.return_value = _make_mock_lookup_response()

    with patch("anki_writer._add_note_and_sync", return_value=99999):
        resp = await ac.post(
            "/add-word",
            json={"word": "Happy", "sentence": "I am very happy today."},
        )

    assert resp.status_code == 200
    data = resp.json()
    assert data["word"] == "happy"      # normalised to lowercase
    assert "note_id" in data
    assert data["note_id"] == 99999
    assert "sense_used" in data
    assert data["sense_used"] == 0      # first (only) sense selected
    assert "definition" in data
    assert data["definition"] != ""


@pytest.mark.asyncio
async def test_add_word_duplicate_returns_422(aw_client):
    """AW-P0-02: POST /add-word — duplicate word rejected.

    Acceptance Criterion: Returns 422 with "duplicate:" in detail.
    """
    ac, mock_ldoce5 = aw_client
    mock_ldoce5.get.return_value = _make_mock_lookup_response()

    with patch(
        "anki_writer._add_note_and_sync",
        side_effect=ValueError(
            "duplicate: cannot create note because it is a duplicate"
        ),
    ):
        resp = await ac.post("/add-word", json={"word": "happy"})

    assert resp.status_code == 422
    assert "duplicate" in resp.json()["detail"]


@pytest.mark.asyncio
async def test_add_word_empty_word_returns_422(aw_client):
    """AW-P0-03: POST /add-word — empty word rejected at validation layer.

    Acceptance Criterion: Returns 422 with "invalid:" in detail.
    No external calls should be made (validation short-circuits before ldoce5-api call).
    """
    ac, mock_ldoce5 = aw_client

    resp = await ac.post("/add-word", json={"word": ""})

    assert resp.status_code == 422
    assert "invalid" in resp.json()["detail"]
    mock_ldoce5.get.assert_not_called()  # ldoce5-api not contacted for invalid input


@pytest.mark.asyncio
async def test_health_returns_required_fields_collection_accessible(aw_client):
    """AW-P0-04: GET /health — returns collection_accessible: true when file exists.

    Acceptance Criterion:
      Returns status: ok, collection_accessible: bool.
      Tests the 'accessible = true' path using a temporary file as collection.
    """
    ac, mock_ldoce5 = aw_client
    mock_ldoce5.get.return_value = Response(200, json={"status": "ok"})

    # Create a temp file to simulate an accessible Anki collection
    with tempfile.NamedTemporaryFile(suffix=".anki2", delete=False) as tmp:
        tmp_path = tmp.name

    try:
        with patch.object(anki_writer, "COLLECTION_PATH", tmp_path):
            resp = await ac.get("/health")

        assert resp.status_code == 200
        data = resp.json()
        assert data["status"] == "ok"
        assert "collection_accessible" in data
        assert data["collection_accessible"] is True
        assert "ldoce5_api_reachable" in data
        assert isinstance(data["ldoce5_api_reachable"], bool)
        assert "last_sync" in data
    finally:
        os.unlink(tmp_path)
