"""
P1 tests for anki-writer (anki_writer.py) — error paths, sense selection, and health.

P1 Tests (High Priority):
  AW-P1-01: POST /add-word success without sentence — uses LDOCE example
  AW-P1-02: POST /add-word with word > 100 chars — returns 422
  AW-P1-03: POST /add-word — ldoce5-api unreachable returns 502
  AW-P1-04: POST /add-word — ldoce5-api returns 404 → anki-writer returns 404
  AW-P1-05: POST /add-word — ldoce5-api returns 5xx → anki-writer returns 502
  AW-P1-06: POST /add-word — Collection write fails (RuntimeError) → 502
  AW-P1-07: POST /add-word — unexpected exception in _add_note_and_sync → 502
  AW-P1-08: POST /add-word with sense_index: 1 — uses specified sense
  AW-P1-09: POST /add-word — note type not found (RuntimeError) → 502
  AW-P1-10: GET /health — collection file not found → collection_accessible: false

Generated by: TEA testarch-automate Workflow (2026-03-03)
"""

from unittest.mock import AsyncMock, MagicMock, patch

import httpx
import pytest
import pytest_asyncio
from httpx import AsyncClient, ASGITransport, Request as HttpxRequest

import anki_writer


# ---------------------------------------------------------------------------
# Test data
# ---------------------------------------------------------------------------

SAMPLE_LDOCE5_RESPONSE = {
    "word": "happy",
    "pronunciation": "/ˈhæp.i/",
    "senses": [
        {
            "index": 0,
            "pos": "adjective",
            "sense_num": 1,
            "definition": "feeling or showing pleasure and contentment",
            "definition_html": (
                '<span class="POS">adjective</span>'
                '<span class="Sense">'
                '<span class="DEF">feeling or showing pleasure and contentment</span>'
                '<span class="EXAMPLE"><span class="BASE">She seemed genuinely happy.</span></span>'
                "</span>"
            ),
            "example": "She seemed genuinely happy.",
            "ai_selected": True,
        }
    ],
    "selected_sense_index": 0,
    "audio": {
        "uk": {"filename": "GB_happy0005.mp3", "url": "/audio/GB_happy0005.mp3"},
        "us": {"filename": "US_happy0005.mp3", "url": "/audio/US_happy0005.mp3"},
    },
    "warning": None,
}

# Multi-sense response for sense_index tests
SAMPLE_MULTI_SENSE_RESPONSE = {
    "word": "run",
    "pronunciation": "/rʌn/",
    "senses": [
        {
            "index": 0,
            "pos": "verb",
            "sense_num": 1,
            "definition": "to move quickly on foot",
            "definition_html": '<span class="DEF">to move quickly on foot</span>',
            "example": "She runs every day.",
            "ai_selected": False,
        },
        {
            "index": 1,
            "pos": "verb",
            "sense_num": 2,
            "definition": "to manage or control something",
            "definition_html": '<span class="DEF">to manage or control something</span>',
            "example": "He runs the department.",
            "ai_selected": True,
        },
    ],
    "selected_sense_index": 1,
    "audio": {
        "uk": {"filename": "GB_run0005.mp3", "url": "/audio/GB_run0005.mp3"},
        "us": {"filename": "US_run0005.mp3", "url": "/audio/US_run0005.mp3"},
    },
    "warning": None,
}


def _make_mock_lookup_response(json_data=None):
    """Return a MagicMock for a successful httpx response.

    Uses MagicMock instead of httpx.Response because httpx ≥0.24 raise_for_status()
    raises RuntimeError when the response has no request attribute set.
    """
    mock_resp = MagicMock()
    mock_resp.status_code = 200
    mock_resp.raise_for_status = MagicMock()
    mock_resp.json.return_value = json_data or SAMPLE_LDOCE5_RESPONSE
    mock_resp.content = b"fake_audio_bytes"
    return mock_resp


def _make_mock_error_response(status_code: int):
    """Return a MagicMock whose raise_for_status() raises httpx.HTTPStatusError."""
    mock_resp = MagicMock()
    mock_resp.status_code = status_code
    mock_resp.raise_for_status.side_effect = httpx.HTTPStatusError(
        f"HTTP {status_code}",
        request=HttpxRequest("GET", "http://test/lookup"),
        response=mock_resp,
    )
    return mock_resp


# ---------------------------------------------------------------------------
# Fixture
# ---------------------------------------------------------------------------


@pytest_asyncio.fixture
async def aw_client():
    """Yield (AsyncClient, mock_ldoce5) for anki-writer P1 tests."""
    mock_ldoce5 = AsyncMock()
    anki_writer.app.state.ldoce5_client = mock_ldoce5

    async with AsyncClient(
        transport=ASGITransport(app=anki_writer.app), base_url="http://test"
    ) as ac:
        yield ac, mock_ldoce5

    try:
        delattr(anki_writer.app.state, "ldoce5_client")
    except AttributeError:
        pass


# ---------------------------------------------------------------------------
# P1 Tests
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_add_word_success_without_sentence(aw_client):
    """AW-P1-01: POST /add-word without sentence — uses LDOCE example as sentence field.

    Acceptance Criterion: Returns 200 with note_id. When no user sentence is
    provided, the LDOCE example from the selected sense is used as the sentence.
    """
    ac, mock_ldoce5 = aw_client
    mock_ldoce5.get.return_value = _make_mock_lookup_response()

    with patch("anki_writer._add_note_and_sync", return_value=88888) as mock_add:
        resp = await ac.post("/add-word", json={"word": "happy"})

    assert resp.status_code == 200
    data = resp.json()
    assert data["word"] == "happy"
    assert data["note_id"] == 88888
    # Verify _add_note_and_sync was called with LDOCE example as sentence
    call_args = mock_add.call_args[0]
    sentence_arg = call_args[3]
    assert "She seemed genuinely happy." in sentence_arg


@pytest.mark.asyncio
async def test_add_word_word_too_long_returns_422(aw_client):
    """AW-P1-02: POST /add-word with word > 100 chars — rejected before any API call.

    Acceptance Criterion: Returns 422 with "invalid:" in detail.
    ldoce5-api must NOT be contacted.
    """
    ac, mock_ldoce5 = aw_client
    long_word = "a" * 101

    resp = await ac.post("/add-word", json={"word": long_word})

    assert resp.status_code == 422
    assert "invalid" in resp.json()["detail"]
    mock_ldoce5.get.assert_not_called()


@pytest.mark.asyncio
async def test_add_word_ldoce5_unreachable_returns_502(aw_client):
    """AW-P1-03: POST /add-word — ldoce5-api unreachable (ConnectError) → 502.

    Acceptance Criterion: Returns 502 with "ldoce5-api is not reachable" in detail.
    """
    ac, mock_ldoce5 = aw_client
    mock_ldoce5.get.side_effect = httpx.ConnectError("Connection refused")

    resp = await ac.post("/add-word", json={"word": "happy"})

    assert resp.status_code == 502
    assert "ldoce5-api is not reachable" in resp.json()["detail"]


@pytest.mark.asyncio
async def test_add_word_ldoce5_returns_404_propagates_404(aw_client):
    """AW-P1-04: POST /add-word — ldoce5-api returns 404 → anki-writer returns 404.

    Acceptance Criterion: Returns 404 with "not found" in detail.
    (ldoce5-api 404 means the word is not in the dictionary.)
    """
    ac, mock_ldoce5 = aw_client
    mock_ldoce5.get.return_value = _make_mock_error_response(404)

    resp = await ac.post("/add-word", json={"word": "xyzunknown"})

    assert resp.status_code == 404
    assert "not found" in resp.json()["detail"]


@pytest.mark.asyncio
async def test_add_word_ldoce5_returns_5xx_propagates_502(aw_client):
    """AW-P1-05: POST /add-word — ldoce5-api returns 5xx → 502.

    Acceptance Criterion: Returns 502 with "ldoce5-api returned an error" in detail.
    """
    ac, mock_ldoce5 = aw_client
    mock_ldoce5.get.return_value = _make_mock_error_response(500)

    resp = await ac.post("/add-word", json={"word": "happy"})

    assert resp.status_code == 502
    assert "ldoce5-api returned an error" in resp.json()["detail"]


@pytest.mark.asyncio
async def test_add_word_collection_write_fails_returns_502(aw_client):
    """AW-P1-06: POST /add-word — Collection write raises RuntimeError → 502.

    Acceptance Criterion: Returns 502 with "anki sync failed" in detail.
    """
    ac, mock_ldoce5 = aw_client
    mock_ldoce5.get.return_value = _make_mock_lookup_response()

    with patch(
        "anki_writer._add_note_and_sync",
        side_effect=RuntimeError("anki collection is corrupt"),
    ):
        resp = await ac.post("/add-word", json={"word": "happy"})

    assert resp.status_code == 502
    assert "anki sync failed" in resp.json()["detail"]


@pytest.mark.asyncio
async def test_add_word_unexpected_exception_returns_502(aw_client):
    """AW-P1-07: POST /add-word — unexpected Exception in _add_note_and_sync → 502.

    Acceptance Criterion: Returns 502 with "anki sync failed" in detail.
    Covers the case where anki-sync-server is down or any other unexpected error.
    """
    ac, mock_ldoce5 = aw_client
    mock_ldoce5.get.return_value = _make_mock_lookup_response()

    with patch(
        "anki_writer._add_note_and_sync",
        side_effect=Exception("sync server connection refused"),
    ):
        resp = await ac.post("/add-word", json={"word": "happy"})

    assert resp.status_code == 502
    assert "anki sync failed" in resp.json()["detail"]


@pytest.mark.asyncio
async def test_add_word_uses_specified_sense_index(aw_client):
    """AW-P1-08: POST /add-word with sense_index: 1 — uses specified sense.

    Acceptance Criterion: sense_used in response is 1 (the caller-specified index),
    not the AI-selected index from ldoce5-api.
    """
    ac, mock_ldoce5 = aw_client
    mock_ldoce5.get.return_value = _make_mock_lookup_response(SAMPLE_MULTI_SENSE_RESPONSE)

    with patch("anki_writer._add_note_and_sync", return_value=99999):
        resp = await ac.post(
            "/add-word",
            json={"word": "run", "sense_index": 1},
        )

    assert resp.status_code == 200
    data = resp.json()
    assert data["sense_used"] == 1


@pytest.mark.asyncio
async def test_add_word_note_type_not_found_returns_502(aw_client):
    """AW-P1-09: POST /add-word — note type not found raises RuntimeError → 502.

    Acceptance Criterion: Returns 502 with "anki sync failed".
    Simulates _add_note_and_sync raising RuntimeError when note type is absent.
    """
    ac, mock_ldoce5 = aw_client
    mock_ldoce5.get.return_value = _make_mock_lookup_response()

    with patch(
        "anki_writer._add_note_and_sync",
        side_effect=RuntimeError("note type 'ODH' not found in collection"),
    ):
        resp = await ac.post("/add-word", json={"word": "happy"})

    assert resp.status_code == 502
    assert "anki sync failed" in resp.json()["detail"]


@pytest.mark.asyncio
async def test_health_collection_not_found_returns_false(aw_client):
    """AW-P1-10: GET /health — non-existent COLLECTION_PATH → collection_accessible: false.

    Acceptance Criterion: Returns 200 with collection_accessible: false when
    the collection file path does not exist on disk.
    """
    ac, mock_ldoce5 = aw_client
    mock_ldoce5.get.return_value = MagicMock(status_code=200)

    with patch.object(anki_writer, "COLLECTION_PATH", "/nonexistent/path/collection.anki2"):
        resp = await ac.get("/health")

    assert resp.status_code == 200
    data = resp.json()
    assert data["status"] == "ok"
    assert data["collection_accessible"] is False
