"""
ATDD: Acceptance tests for ldoce5-api (main.py) — Dual-service architecture.

TDD Phase: These tests define the expected API contract for ldoce5-api after
migration from AnkiConnect to the dual-service architecture.

P0 Tests (Critical Path):
  LDO-P0-01: GET /lookup?word=happy — success, returns senses + audio + pronunciation
  LDO-P0-02: GET /lookup?word=unknown — word not found returns 404
  LDO-P0-03: GET /health — returns status: ok, mdx_loaded: true

Generated by: TEA ATDD Workflow (2026-03-03)
Story: iphone-anki-sync dual-service migration
"""

import os
import sys
from unittest.mock import MagicMock

import pytest
import pytest_asyncio
from httpx import AsyncClient, ASGITransport

# ---------------------------------------------------------------------------
# Module-level setup: inject mocks BEFORE importing main.
# mdict_utils requires actual .mdx/.mdd files on disk; we mock the module so
# tests run without the binary dictionary files being present.
# ---------------------------------------------------------------------------

os.environ["LDOCE5_MDX_PATH"] = "/fake/LDOCE5.mdx"
os.environ.setdefault("LDOCE5_MDD_PATH", "/fake/LDOCE5.mdd")

_mock_mdict_utils = MagicMock()
_mock_mdict_utils.reader.query = MagicMock(return_value=b"")
sys.modules.setdefault("mdict_utils", _mock_mdict_utils)
sys.modules.setdefault("mdict_utils.reader", _mock_mdict_utils.reader)

import main  # noqa: E402 — must come after sys.modules patch


# ---------------------------------------------------------------------------
# Test data: minimal LDOCE5 HTML covering audio, pronunciation, and one sense
# ---------------------------------------------------------------------------

LDOCE5_HAPPY_HTML = (
    '<a href="sound://GB_happy0005.spx"></a>'
    '<a href="sound://US_happy0005.spx"></a>'
    '<span class="PRON">ˈhæp.i</span>'
    '<span class="POS">adjective</span>'
    '<span class="Sense">'
    '<span class="DEF">feeling or showing pleasure and contentment</span>'
    '<span class="EXAMPLE"><span class="BASE">She seemed genuinely happy.</span></span>'
    "</span>"
)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest_asyncio.fixture
async def ldoce5_client():
    """Yield (AsyncClient, mock_mdx, mock_mdd) for ldoce5-api tests.

    Sets app.state directly — ASGITransport (httpx 0.28) does NOT trigger
    the ASGI lifespan, so we bypass lifespan entirely and control state ourselves.

    LLM client is set to None to disable AI sense disambiguation in all tests
    (avoids needing LLM_API_KEY).
    """
    mock_mdx = MagicMock()
    mock_mdd = MagicMock()

    main.app.state.mdx_builder = mock_mdx
    main.app.state.mdd_wrapper = mock_mdd
    main.app.state.llm_client = None  # LLM disabled — no API key in test env

    async with AsyncClient(
        transport=ASGITransport(app=main.app), base_url="http://test"
    ) as ac:
        yield ac, mock_mdx, mock_mdd

    # Clean up state between tests
    for key in ("mdx_builder", "mdd_wrapper", "llm_client"):
        try:
            delattr(main.app.state, key)
        except AttributeError:
            pass


# ---------------------------------------------------------------------------
# P0 Tests — Critical path (must all pass before any other work proceeds)
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_lookup_success_returns_required_fields(ldoce5_client):
    """LDO-P0-01: GET /lookup?word=happy — success case.

    Acceptance Criterion:
      API returns word, senses[], audio, pronunciation, selected_sense_index
      for a known word. Each sense must have index, pos, definition,
      definition_html, example, and ai_selected fields.
      Audio must include at least uk.url pointing to /audio/ endpoint.
    """
    ac, mock_mdx, _ = ldoce5_client
    mock_mdx.mdx_lookup.return_value = [LDOCE5_HAPPY_HTML]

    resp = await ac.get("/lookup", params={"word": "happy"})

    assert resp.status_code == 200
    data = resp.json()

    # Top-level required fields
    assert data["word"] == "happy"
    assert "pronunciation" in data
    assert isinstance(data["senses"], list)
    assert len(data["senses"]) >= 1
    assert "audio" in data
    assert "selected_sense_index" in data

    # Sense structure — all fields required by anki-writer consumer
    sense = data["senses"][0]
    assert "index" in sense
    assert "pos" in sense
    assert "definition" in sense
    assert "definition_html" in sense
    assert "example" in sense
    assert "ai_selected" in sense

    # Audio URLs must point to the /audio/ serving endpoint
    assert data["audio"]["uk"] is not None
    assert "url" in data["audio"]["uk"]
    assert data["audio"]["uk"]["url"].startswith("/audio/")
    assert data["audio"]["uk"]["url"].endswith(".mp3")


@pytest.mark.asyncio
async def test_lookup_not_found_returns_404(ldoce5_client):
    """LDO-P0-02: GET /lookup?word=unknown — word not found.

    Acceptance Criterion: API returns 404 with "not found" in detail.
    """
    ac, mock_mdx, _ = ldoce5_client
    mock_mdx.mdx_lookup.return_value = []  # word not in dictionary

    resp = await ac.get("/lookup", params={"word": "xyznonexistent"})

    assert resp.status_code == 404
    assert "not found" in resp.json()["detail"]


@pytest.mark.asyncio
async def test_health_returns_ok_with_required_fields(ldoce5_client):
    """LDO-P0-03: GET /health — all components loaded returns status: ok.

    Acceptance Criterion:
      Health endpoint returns status: ok, mdx_loaded: true (mdx_builder set),
      plus mdd_loaded and llm_enabled boolean fields.
    """
    ac, _, _ = ldoce5_client  # fixture already sets mdx_builder + mdd_wrapper

    resp = await ac.get("/health")

    assert resp.status_code == 200
    data = resp.json()
    assert data["status"] == "ok"
    assert data["mdx_loaded"] is True    # mock_mdx is truthy MagicMock
    assert "mdd_loaded" in data           # mdd_wrapper set in fixture (truthy)
    assert "llm_enabled" in data          # False — no LLM_API_KEY in test env
    assert isinstance(data["llm_enabled"], bool)
