"""
P1 tests for ldoce5-api (main.py) — validation, audio endpoints, and LLM fallback.

P1 Tests (High Priority):
  LDO-P1-01: GET /lookup with sentence → selected_sense_index reflects AI pick
  LDO-P1-02: GET /lookup — audio UK present; US present as fallback
  LDO-P1-03: GET /lookup?word= — empty word returns 422 with "invalid:"
  LDO-P1-04: GET /lookup?word=<101chars> — word too long returns 422
  LDO-P1-05: GET /audio/GB_happy0005.mp3 — served with audio/mpeg content-type
  LDO-P1-06: GET /audio/nonexistent.mp3 — returns 404 when not in MDD
  LDO-P1-07: GET /lookup — LLM disabled (no API key) still returns valid response

Generated by: TEA testarch-automate Workflow (2026-03-03)
"""

import os
import sys
from unittest.mock import MagicMock, patch

import pytest
import pytest_asyncio
from httpx import AsyncClient, ASGITransport

# ---------------------------------------------------------------------------
# Module-level setup: same preamble as test_ldoce5_api.py.
# setdefault() is safe to call again — no-op if already set.
# ---------------------------------------------------------------------------

os.environ["LDOCE5_MDX_PATH"] = "/fake/LDOCE5.mdx"
os.environ.setdefault("LDOCE5_MDD_PATH", "/fake/LDOCE5.mdd")

_mock_mdict_utils = MagicMock()
_mock_mdict_utils.reader.query = MagicMock(return_value=b"")
sys.modules.setdefault("mdict_utils", _mock_mdict_utils)
sys.modules.setdefault("mdict_utils.reader", _mock_mdict_utils.reader)

import main  # noqa: E402


# ---------------------------------------------------------------------------
# HTML fixtures
# ---------------------------------------------------------------------------

LDOCE5_HAPPY_HTML = (
    '<a href="sound://GB_happy0005.spx"></a>'
    '<a href="sound://US_happy0005.spx"></a>'
    '<span class="PRON">ˈhæp.i</span>'
    '<span class="POS">adjective</span>'
    '<span class="Sense">'
    '<span class="DEF">feeling or showing pleasure and contentment</span>'
    '<span class="EXAMPLE"><span class="BASE">She seemed genuinely happy.</span></span>'
    "</span>"
)

# Multi-sense HTML for testing AI sense selection
LDOCE5_MULTI_SENSE_HTML = (
    '<span class="POS">verb</span>'
    '<span class="Sense">'
    '<span class="DEF">to move quickly on foot</span>'
    '<span class="EXAMPLE"><span class="BASE">She runs every day.</span></span>'
    "</span>"
    '<span class="Sense">'
    '<span class="DEF">to manage or control something</span>'
    '<span class="EXAMPLE"><span class="BASE">He runs the department.</span></span>'
    "</span>"
)


# ---------------------------------------------------------------------------
# Fixture
# ---------------------------------------------------------------------------


@pytest_asyncio.fixture
async def ldoce5_client():
    """Yield (AsyncClient, mock_mdx, mock_mdd) with mdd_wrapper set."""
    mock_mdx = MagicMock()
    mock_mdd = MagicMock()

    main.app.state.mdx_builder = mock_mdx
    main.app.state.mdd_wrapper = mock_mdd
    main.app.state.llm_client = None

    async with AsyncClient(
        transport=ASGITransport(app=main.app), base_url="http://test"
    ) as ac:
        yield ac, mock_mdx, mock_mdd

    for key in ("mdx_builder", "mdd_wrapper", "llm_client"):
        try:
            delattr(main.app.state, key)
        except AttributeError:
            pass


# ---------------------------------------------------------------------------
# P1 Tests
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_lookup_with_sentence_ai_selection_reflected_in_response(ldoce5_client):
    """LDO-P1-01: AI pick for sense index is reflected in selected_sense_index.

    Acceptance Criterion:
      When LLM_API_KEY is set and a sentence is provided, _ai_pick_sense is
      called and its result appears in selected_sense_index and senses[n].ai_selected.
    """
    ac, mock_mdx, _ = ldoce5_client
    mock_mdx.mdx_lookup.return_value = [LDOCE5_MULTI_SENSE_HTML]

    with patch("main.LLM_API_KEY", "fake-key"):
        with patch("main._ai_pick_sense", return_value=1) as mock_ai:
            resp = await ac.get(
                "/lookup",
                params={"word": "run", "sentence": "She runs the department."},
            )

    assert resp.status_code == 200
    data = resp.json()
    assert data["selected_sense_index"] == 1
    assert data["senses"][1]["ai_selected"] is True
    assert data["senses"][0]["ai_selected"] is False
    mock_ai.assert_called_once()


@pytest.mark.asyncio
async def test_lookup_audio_contains_uk_and_us_urls(ldoce5_client):
    """LDO-P1-02: GET /lookup — audio dict contains both UK and US URL entries.

    Acceptance Criterion: audio.uk.url and audio.us.url both present,
    pointing to /audio/ endpoints, UK prefixed GB_ and US prefixed US_.
    """
    ac, mock_mdx, _ = ldoce5_client
    mock_mdx.mdx_lookup.return_value = [LDOCE5_HAPPY_HTML]

    resp = await ac.get("/lookup", params={"word": "happy"})

    assert resp.status_code == 200
    audio = resp.json()["audio"]
    assert audio["uk"] is not None
    assert audio["us"] is not None
    assert audio["uk"]["url"].startswith("/audio/GB_")
    assert audio["us"]["url"].startswith("/audio/US_")


@pytest.mark.asyncio
async def test_lookup_empty_word_returns_422(ldoce5_client):
    """LDO-P1-03: GET /lookup?word= — empty word rejected before dictionary lookup.

    Acceptance Criterion: Returns 422 with "invalid:" in detail.
    No dictionary lookup is performed.
    """
    ac, mock_mdx, _ = ldoce5_client

    resp = await ac.get("/lookup", params={"word": ""})

    assert resp.status_code == 422
    assert "invalid" in resp.json()["detail"]
    mock_mdx.mdx_lookup.assert_not_called()


@pytest.mark.asyncio
async def test_lookup_word_too_long_returns_422(ldoce5_client):
    """LDO-P1-04: GET /lookup with word > 100 chars — rejected before lookup.

    Acceptance Criterion: Returns 422 with "invalid:" in detail.
    """
    ac, mock_mdx, _ = ldoce5_client
    long_word = "a" * 101

    resp = await ac.get("/lookup", params={"word": long_word})

    assert resp.status_code == 422
    assert "invalid" in resp.json()["detail"]
    mock_mdx.mdx_lookup.assert_not_called()


@pytest.mark.asyncio
async def test_audio_endpoint_serves_mp3_content(ldoce5_client):
    """LDO-P1-05: GET /audio/GB_happy0005.mp3 — returns audio/mpeg with content.

    Acceptance Criterion: Status 200, Content-Type contains 'audio',
    response body is non-empty (MP3 bytes).
    """
    ac, _, mock_mdd = ldoce5_client
    mock_mdd.mdd_lookup.return_value = b"fake_spx_audio_bytes"

    with patch("main._spx_to_mp3", return_value=(b"fake_mp3_bytes", None)):
        resp = await ac.get("/audio/GB_happy0005.mp3")

    assert resp.status_code == 200
    assert "audio" in resp.headers["content-type"]
    assert len(resp.content) > 0


@pytest.mark.asyncio
async def test_audio_endpoint_returns_404_when_not_in_mdd(ldoce5_client):
    """LDO-P1-06: GET /audio/nonexistent.mp3 — 404 when file not in MDD.

    Acceptance Criterion: Returns 404 with "not found" in detail.
    """
    ac, _, mock_mdd = ldoce5_client
    mock_mdd.mdd_lookup.return_value = None

    resp = await ac.get("/audio/nonexistent.mp3")

    assert resp.status_code == 404
    assert "not found" in resp.json()["detail"]


@pytest.mark.asyncio
async def test_lookup_llm_disabled_fallback_returns_valid_response(ldoce5_client):
    """LDO-P1-07: GET /lookup — when LLM_API_KEY is empty, AI is skipped.

    Acceptance Criterion: Response is 200 with selected_sense_index: 0 (default).
    AI sense disambiguation must NOT be invoked.
    """
    ac, mock_mdx, _ = ldoce5_client
    mock_mdx.mdx_lookup.return_value = [LDOCE5_MULTI_SENSE_HTML]

    # Explicitly disable LLM key so AI branch is skipped
    with patch("main.LLM_API_KEY", ""):
        with patch("main._ai_pick_sense") as mock_ai:
            resp = await ac.get(
                "/lookup",
                params={"word": "run", "sentence": "She runs fast every morning."},
            )

    assert resp.status_code == 200
    data = resp.json()
    assert data["selected_sense_index"] == 0  # fallback to first sense
    assert len(data["senses"]) == 2
    assert data["warning"] is None
    mock_ai.assert_not_called()  # AI not invoked when LLM_API_KEY is empty
