"""
P2 tests for ldoce5-api (main.py) — secondary paths + unit tests for pure functions.

P2 API Tests (Medium Priority):
  LDO-P2-01: GET /lookup — multiple senses returned for polysemous word
  LDO-P2-02: GET /lookup — no audio in HTML → audio: {uk: None, us: None}
  LDO-P2-03: GET /health — MDX not loaded returns mdx_loaded: false
  LDO-P2-04: GET /lookup — response always includes pronunciation field
  LDO-P2-05: GET /audio — MDD not loaded returns 404 "audio not available"

Unit Tests (Medium Priority):
  UNIT-LDO-01: _extract_audio_filenames() — both UK and US present
  UNIT-LDO-02: _extract_audio_filenames() — UK only (no US)
  UNIT-LDO-03: _extract_audio_filenames() — neither UK nor US
  UNIT-LDO-04: _extract_senses() — multiple senses extracted with correct structure
  UNIT-LDO-05: _extract_reading() — pronunciation extracted correctly

Generated by: TEA testarch-automate Workflow (2026-03-03)
"""

import os
import sys
from unittest.mock import MagicMock, patch

import pytest
import pytest_asyncio
from httpx import AsyncClient, ASGITransport

# ---------------------------------------------------------------------------
# Module-level setup (same safe preamble as other ldoce5 test files)
# ---------------------------------------------------------------------------

os.environ["LDOCE5_MDX_PATH"] = "/fake/LDOCE5.mdx"
os.environ.setdefault("LDOCE5_MDD_PATH", "/fake/LDOCE5.mdd")

_mock_mdict_utils = MagicMock()
_mock_mdict_utils.reader.query = MagicMock(return_value=b"")
sys.modules.setdefault("mdict_utils", _mock_mdict_utils)
sys.modules.setdefault("mdict_utils.reader", _mock_mdict_utils.reader)

import main  # noqa: E402


# ---------------------------------------------------------------------------
# HTML fixtures
# ---------------------------------------------------------------------------

LDOCE5_MULTI_SENSE_HTML = (
    '<a href="sound://GB_run0005.spx"></a>'
    '<span class="PRON">rʌn</span>'
    '<span class="POS">verb</span>'
    '<span class="Sense">'
    '<span class="DEF">to move quickly on foot</span>'
    '<span class="EXAMPLE"><span class="BASE">She runs every day.</span></span>'
    "</span>"
    '<span class="Sense">'
    '<span class="DEF">to manage or control something</span>'
    '<span class="EXAMPLE"><span class="BASE">He runs the department.</span></span>'
    "</span>"
)

LDOCE5_NO_AUDIO_HTML = (
    '<span class="PRON">ˈhæp.i</span>'
    '<span class="POS">adjective</span>'
    '<span class="Sense">'
    '<span class="DEF">feeling or showing pleasure</span>'
    "</span>"
)

LDOCE5_UK_ONLY_HTML = (
    '<a href="sound://GB_run0005.spx"></a>'
    '<span class="POS">verb</span>'
    '<span class="Sense"><span class="DEF">to move quickly</span></span>'
)


# ---------------------------------------------------------------------------
# Fixture
# ---------------------------------------------------------------------------


@pytest_asyncio.fixture
async def ldoce5_client():
    """Yield (AsyncClient, mock_mdx, mock_mdd)."""
    mock_mdx = MagicMock()
    mock_mdd = MagicMock()

    main.app.state.mdx_builder = mock_mdx
    main.app.state.mdd_wrapper = mock_mdd
    main.app.state.llm_client = None

    async with AsyncClient(
        transport=ASGITransport(app=main.app), base_url="http://test"
    ) as ac:
        yield ac, mock_mdx, mock_mdd

    for key in ("mdx_builder", "mdd_wrapper", "llm_client"):
        try:
            delattr(main.app.state, key)
        except AttributeError:
            pass


# ---------------------------------------------------------------------------
# P2 API Tests
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_lookup_polysemous_word_returns_all_senses(ldoce5_client):
    """LDO-P2-01: GET /lookup — multiple senses all present in response.

    Acceptance Criterion: senses list has ≥2 items; each sense has required fields.
    """
    ac, mock_mdx, _ = ldoce5_client
    mock_mdx.mdx_lookup.return_value = [LDOCE5_MULTI_SENSE_HTML]

    resp = await ac.get("/lookup", params={"word": "run"})

    assert resp.status_code == 200
    data = resp.json()
    assert isinstance(data["senses"], list)
    assert len(data["senses"]) >= 2
    for i, sense in enumerate(data["senses"]):
        assert sense["index"] == i
        assert "definition" in sense
        assert "definition_html" in sense
        assert "pos" in sense


@pytest.mark.asyncio
async def test_lookup_no_audio_in_html_returns_null_audio(ldoce5_client):
    """LDO-P2-02: GET /lookup — word with no audio links → audio values are None.

    Acceptance Criterion: audio.uk is None and audio.us is None when HTML has
    no sound:// links.
    """
    ac, mock_mdx, _ = ldoce5_client
    mock_mdx.mdx_lookup.return_value = [LDOCE5_NO_AUDIO_HTML]

    resp = await ac.get("/lookup", params={"word": "happy"})

    assert resp.status_code == 200
    audio = resp.json()["audio"]
    assert audio["uk"] is None
    assert audio["us"] is None


@pytest.mark.asyncio
async def test_health_mdx_not_loaded_returns_false(ldoce5_client):
    """LDO-P2-03: GET /health — MDX not loaded returns mdx_loaded: false.

    Acceptance Criterion: mdx_loaded: false when mdx_builder is not set.
    """
    ac, _, _ = ldoce5_client

    # Override mdx_builder to None to simulate unloaded state
    main.app.state.mdx_builder = None

    resp = await ac.get("/health")

    assert resp.status_code == 200
    data = resp.json()
    assert data["status"] == "ok"
    assert data["mdx_loaded"] is False


@pytest.mark.asyncio
async def test_lookup_response_always_includes_pronunciation(ldoce5_client):
    """LDO-P2-04: GET /lookup — pronunciation field always present in response.

    Acceptance Criterion: pronunciation field is present, formatted as /.../.
    """
    ac, mock_mdx, _ = ldoce5_client
    mock_mdx.mdx_lookup.return_value = [LDOCE5_MULTI_SENSE_HTML]

    resp = await ac.get("/lookup", params={"word": "run"})

    assert resp.status_code == 200
    data = resp.json()
    assert "pronunciation" in data
    pronunciation = data["pronunciation"]
    assert pronunciation.startswith("/")
    assert pronunciation.endswith("/")


@pytest.mark.asyncio
async def test_audio_endpoint_returns_404_when_mdd_not_loaded(ldoce5_client):
    """LDO-P2-05: GET /audio — MDD not loaded returns 404 "audio not available".

    Acceptance Criterion: Returns 404 with "audio not available" in detail
    when mdd_wrapper is None (MDD not loaded at startup).
    """
    ac, _, _ = ldoce5_client
    main.app.state.mdd_wrapper = None  # simulate MDD not loaded

    resp = await ac.get("/audio/GB_happy0005.mp3")

    assert resp.status_code == 404
    assert "audio not available" in resp.json()["detail"]


# ---------------------------------------------------------------------------
# Unit Tests for pure extraction functions
# ---------------------------------------------------------------------------


def test_extract_audio_filenames_both_uk_and_us():
    """UNIT-LDO-01: _extract_audio_filenames() — both UK (GB_) and US (US_) present."""
    html = (
        '<a href="sound://GB_happy0005.spx"></a>'
        '<a href="sound://US_happy0005.spx"></a>'
    )

    result = main._extract_audio_filenames(html)

    assert result["uk"] == "GB_happy0005.spx"
    assert result["us"] == "US_happy0005.spx"


def test_extract_audio_filenames_uk_only():
    """UNIT-LDO-02: _extract_audio_filenames() — UK only → us: None."""
    html = '<a href="sound://GB_run0005.spx"></a>'

    result = main._extract_audio_filenames(html)

    assert result["uk"] == "GB_run0005.spx"
    assert result["us"] is None


def test_extract_audio_filenames_no_audio():
    """UNIT-LDO-03: _extract_audio_filenames() — no audio links → both None."""
    html = '<span class="POS">noun</span><span class="DEF">a test word</span>'

    result = main._extract_audio_filenames(html)

    assert result["uk"] is None
    assert result["us"] is None


def test_extract_senses_returns_correct_structure():
    """UNIT-LDO-04: _extract_senses() — each sense has all required fields."""
    html = (
        '<span class="POS">adjective</span>'
        '<span class="Sense">'
        '<span class="DEF">feeling pleasure</span>'
        '<span class="EXAMPLE"><span class="BASE">She was happy.</span></span>'
        "</span>"
        '<span class="Sense">'
        '<span class="DEF">willing to do something</span>'
        '<span class="EXAMPLE"><span class="BASE">I am happy to help.</span></span>'
        "</span>"
    )

    senses = main._extract_senses(html)

    assert len(senses) == 2
    for sense in senses:
        assert "pos" in sense
        assert "sense_num" in sense
        assert "definition" in sense
        assert "example" in sense
        assert "definition_html" in sense
    assert senses[0]["definition"] == "feeling pleasure"
    assert senses[1]["definition"] == "willing to do something"
    assert senses[0]["example"] == "She was happy."
    assert senses[0]["pos"] == "adjective"


def test_extract_reading_returns_ipa_pronunciation():
    """UNIT-LDO-05: _extract_reading() — IPA phonetic extracted and wrapped in slashes."""
    html = '<span class="PRON">ˈhæp.i</span>'

    result = main._extract_reading(html)

    assert result == "/ˈhæp.i/"


def test_extract_reading_returns_empty_when_no_pron():
    """UNIT-LDO-05b: _extract_reading() — empty string when no PRON span found."""
    html = '<span class="POS">adjective</span>'

    result = main._extract_reading(html)

    assert result == ""
