"""
P2 tests for anki-writer (anki_writer.py) — secondary paths and edge cases.

P2 Tests (Medium Priority):
  AW-P2-01: POST /add-word — audio filename and bytes passed to _add_note_and_sync
  AW-P2-02: POST /add-word — audio fetch failure handled silently; card still created
  AW-P2-03: POST /add-word with sentence — combined with LDOCE example in sentence field
  AW-P2-04: POST /add-word with mixed-case word — normalized to lowercase
  AW-P2-05: POST /add-word with explicit sense_index: 0 — sense_used: 0
  AW-P2-06: POST /add-word with out-of-range sense_index — clamped to last sense
  AW-P2-07: GET /health — ldoce5-api unreachable → ldoce5_api_reachable: false

Generated by: TEA testarch-automate Workflow (2026-03-03)
"""

from unittest.mock import AsyncMock, MagicMock, patch

import pytest
import pytest_asyncio
from httpx import AsyncClient, ASGITransport

import anki_writer


# ---------------------------------------------------------------------------
# Test data
# ---------------------------------------------------------------------------

SAMPLE_LDOCE5_RESPONSE = {
    "word": "happy",
    "pronunciation": "/ˈhæp.i/",
    "senses": [
        {
            "index": 0,
            "pos": "adjective",
            "sense_num": 1,
            "definition": "feeling or showing pleasure and contentment",
            "definition_html": (
                '<span class="POS">adjective</span>'
                '<span class="Sense">'
                '<span class="DEF">feeling or showing pleasure and contentment</span>'
                '<span class="EXAMPLE"><span class="BASE">She seemed genuinely happy.</span></span>'
                "</span>"
            ),
            "example": "She seemed genuinely happy.",
            "ai_selected": True,
        }
    ],
    "selected_sense_index": 0,
    "audio": {
        "uk": {"filename": "GB_happy0005.mp3", "url": "/audio/GB_happy0005.mp3"},
        "us": {"filename": "US_happy0005.mp3", "url": "/audio/US_happy0005.mp3"},
    },
    "warning": None,
}

SAMPLE_MULTI_SENSE_RESPONSE = {
    "word": "run",
    "pronunciation": "/rʌn/",
    "senses": [
        {
            "index": 0,
            "pos": "verb",
            "sense_num": 1,
            "definition": "to move quickly on foot",
            "definition_html": '<span class="DEF">to move quickly on foot</span>',
            "example": "She runs every day.",
            "ai_selected": False,
        },
        {
            "index": 1,
            "pos": "verb",
            "sense_num": 2,
            "definition": "to manage or control something",
            "definition_html": '<span class="DEF">to manage or control something</span>',
            "example": "He runs the department.",
            "ai_selected": True,
        },
    ],
    "selected_sense_index": 1,
    "audio": {
        "uk": {"filename": "GB_run0005.mp3", "url": "/audio/GB_run0005.mp3"},
        "us": None,
    },
    "warning": None,
}


def _make_mock_lookup_response(json_data=None):
    """Return a MagicMock for a successful httpx response."""
    mock_resp = MagicMock()
    mock_resp.status_code = 200
    mock_resp.raise_for_status = MagicMock()
    mock_resp.json.return_value = json_data or SAMPLE_LDOCE5_RESPONSE
    mock_resp.content = b"fake_audio_bytes"
    return mock_resp


# ---------------------------------------------------------------------------
# Fixture
# ---------------------------------------------------------------------------


@pytest_asyncio.fixture
async def aw_client():
    """Yield (AsyncClient, mock_ldoce5) for anki-writer P2 tests."""
    mock_ldoce5 = AsyncMock()
    anki_writer.app.state.ldoce5_client = mock_ldoce5

    async with AsyncClient(
        transport=ASGITransport(app=anki_writer.app), base_url="http://test"
    ) as ac:
        yield ac, mock_ldoce5

    try:
        delattr(anki_writer.app.state, "ldoce5_client")
    except AttributeError:
        pass


# ---------------------------------------------------------------------------
# P2 Tests
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_add_word_passes_audio_filename_and_bytes_to_sync(aw_client):
    """AW-P2-01: POST /add-word — audio filename (.mp3) and bytes passed to _add_note_and_sync.

    Acceptance Criterion: _add_note_and_sync is called with audio_filename ending
    in .mp3 and non-empty audio_data bytes.
    """
    ac, mock_ldoce5 = aw_client
    mock_ldoce5.get.return_value = _make_mock_lookup_response()

    with patch("anki_writer._add_note_and_sync", return_value=99999) as mock_add:
        resp = await ac.post("/add-word", json={"word": "happy"})

    assert resp.status_code == 200
    call_args = mock_add.call_args[0]
    audio_filename_arg = call_args[4]   # 5th positional arg
    audio_data_arg = call_args[5]       # 6th positional arg
    assert audio_filename_arg is not None
    assert audio_filename_arg.endswith(".mp3")
    assert audio_data_arg == b"fake_audio_bytes"


@pytest.mark.asyncio
async def test_add_word_audio_fetch_failure_card_still_created(aw_client):
    """AW-P2-02: POST /add-word — audio fetch failure is silent; card still created.

    Acceptance Criterion: Returns 200 with note_id even when the audio fetch
    raises an exception. Audio failure is logged but not propagated.
    """
    ac, mock_ldoce5 = aw_client

    # First call (/lookup) succeeds; second call (audio) raises Exception
    mock_ldoce5.get.side_effect = [
        _make_mock_lookup_response(),
        Exception("audio server timeout"),
    ]

    with patch("anki_writer._add_note_and_sync", return_value=99999) as mock_add:
        resp = await ac.post("/add-word", json={"word": "happy"})

    assert resp.status_code == 200
    assert resp.json()["note_id"] == 99999
    # _add_note_and_sync called with audio_filename=None, audio_data=None
    call_args = mock_add.call_args[0]
    assert call_args[4] is None   # audio_filename
    assert call_args[5] is None   # audio_data


@pytest.mark.asyncio
async def test_add_word_sentence_combined_with_ldoce_example(aw_client):
    """AW-P2-03: POST /add-word with sentence — sentence field combines user input + LDOCE example.

    Acceptance Criterion: _add_note_and_sync receives sentence containing both
    the user's sentence and the LDOCE example, separated by newlines and "— LDOCE:".
    """
    ac, mock_ldoce5 = aw_client
    mock_ldoce5.get.return_value = _make_mock_lookup_response()

    with patch("anki_writer._add_note_and_sync", return_value=99999) as mock_add:
        resp = await ac.post(
            "/add-word",
            json={"word": "happy", "sentence": "He is happy today."},
        )

    assert resp.status_code == 200
    call_args = mock_add.call_args[0]
    sentence_arg = call_args[3]
    assert "He is happy today." in sentence_arg
    assert "— LDOCE:" in sentence_arg
    assert "She seemed genuinely happy." in sentence_arg


@pytest.mark.asyncio
async def test_add_word_mixed_case_word_normalized_to_lowercase(aw_client):
    """AW-P2-04: POST /add-word with mixed-case "HAPPY" — response word is "happy".

    Acceptance Criterion: word in response is lowercased regardless of input casing.
    (Complements P0-01 which tests "Happy" → "happy".)
    """
    ac, mock_ldoce5 = aw_client
    mock_ldoce5.get.return_value = _make_mock_lookup_response()

    with patch("anki_writer._add_note_and_sync", return_value=99999):
        resp = await ac.post("/add-word", json={"word": "HAPPY"})

    assert resp.status_code == 200
    assert resp.json()["word"] == "happy"


@pytest.mark.asyncio
async def test_add_word_explicit_sense_index_zero(aw_client):
    """AW-P2-05: POST /add-word with sense_index: 0 — sense_used: 0 in response.

    Acceptance Criterion: Explicit sense_index=0 overrides AI selection and
    returns sense_used: 0.
    """
    ac, mock_ldoce5 = aw_client
    mock_ldoce5.get.return_value = _make_mock_lookup_response()

    with patch("anki_writer._add_note_and_sync", return_value=99999):
        resp = await ac.post(
            "/add-word",
            json={"word": "happy", "sense_index": 0},
        )

    assert resp.status_code == 200
    assert resp.json()["sense_used"] == 0


@pytest.mark.asyncio
async def test_add_word_out_of_range_sense_index_clamped_to_last(aw_client):
    """AW-P2-06: POST /add-word with sense_index beyond list → clamped to last sense.

    Acceptance Criterion: sense_used equals the index of the last available sense
    (not an error, just clamped via max(0, min(idx, len-1))).
    """
    ac, mock_ldoce5 = aw_client
    mock_ldoce5.get.return_value = _make_mock_lookup_response(SAMPLE_MULTI_SENSE_RESPONSE)

    with patch("anki_writer._add_note_and_sync", return_value=99999):
        resp = await ac.post(
            "/add-word",
            json={"word": "run", "sense_index": 10},  # only 2 senses (0, 1)
        )

    assert resp.status_code == 200
    assert resp.json()["sense_used"] == 1  # clamped to last index


@pytest.mark.asyncio
async def test_health_ldoce5_unreachable_returns_false(aw_client):
    """AW-P2-07: GET /health — ldoce5-api unreachable → ldoce5_api_reachable: false.

    Acceptance Criterion: Returns 200 with ldoce5_api_reachable: false when
    the ldoce5_client.get() raises an exception.
    """
    ac, mock_ldoce5 = aw_client
    mock_ldoce5.get.side_effect = Exception("connection refused")

    resp = await ac.get("/health")

    assert resp.status_code == 200
    data = resp.json()
    assert data["status"] == "ok"
    assert data["ldoce5_api_reachable"] is False
